[profile.default]
src = "packages/contracts/src"
test = "packages/contracts/test"
script = "packages/contracts/script"
out = "packages/contracts/out"
libs = ["packages/contracts/lib"]
viaIR = true
remappings = [
  "@ens-contracts=node_modules/@ensdomains/ens-contracts/contracts",
  "@openzeppelin=node_modules/@openzeppelin",
  "@ensdomains=packages/contracts/lib",
  "forge-std=packages/contracts/lib/forge-std/src",
  "@eth-optimism/contracts-bedrock/src/libraries=packages/contracts/lib/optimism-bedrock-contracts",
  "@nitro-contracts=node_modules/@arbitrum/nitro-contracts",
  "@evmgateway=packages/contracts/src/evmgateway",
]

ignored_warnings_from = [
  "node_modules/",
  "packages/contracts/lib/**",
  "**/src/evmgateway/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
rpc_url = "${RPC_URL}"
arbitrum_rpc_url = "${ARBITRUM_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
