[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
remappings = [
  "@ens-contracts=lib/ens-contracts/contracts",
  "@openzeppelin=lib/openzeppelin-contracts",
  "@ensdomains=lib",
  "forge-std=lib/forge-std/src",
  "@eth-optimism/contracts-bedrock/src/libraries=lib/optimism-bedrock-contracts"
]
ignored_warnings_from = ["lib/**"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
